### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by droppey** [RainWolf0603/RainWolfBot#1]
![Eastern-boxelder-bug](https://user-images.githubusercontent.com/26809331/127849491-9f13b921-15c2-43f7-8706-2f17593d80fd.jpg)

**Comment by RainWolf0603** [comment]
幹你娘

**Comment by droppey** [comment]
> 
> 
> 幹你娘

草

**Comment by RainWolf0603** [comment]
牛阿你

**Comment by RainWolf0603** [comment]
![image](https://user-images.githubusercontent.com/49824542/129469717-756af0b2-213d-45b9-a176-932688a70df0.jpeg)

**Comment by droppey** [comment]
sorry i dont speak KIMCHI
